// SPDX-License-Identifier: Apache-2.0
// Package console embeds the operator console in the standalone gateway binary.
package console

import (
	"embed"
	"io/fs"
	"net/http"
	"path"
	"strings"
)

// Assets are generated by `cd console && npm ci && npm run build`.
// They are deliberately tracked so Go-only builds produce a runnable console.
//
//go:embed assets
var embedded embed.FS

// Handler serves /console/ including browser navigation to SPA routes. Missing
// asset paths return 404 instead of an HTML success response. API paths never
// enter this handler and remain authenticated by the server composition.
func Handler() http.Handler {
	assets, err := fs.Sub(embedded, "assets")
	if err != nil {
		panic(err)
	}
	files := http.FileServer(http.FS(assets))
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			w.WriteHeader(http.StatusMethodNotAllowed)
			return
		}
		if r.URL.Path == "/console" {
			http.Redirect(w, r, "/console/", http.StatusPermanentRedirect)
			return
		}
		if !strings.HasPrefix(r.URL.Path, "/console/") {
			http.NotFound(w, r)
			return
		}
		name := strings.TrimPrefix(r.URL.Path, "/console/")
		if strings.Contains(name, "..") || strings.Contains(name, "\\") {
			http.NotFound(w, r)
			return
		}
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("Referrer-Policy", "no-referrer")
		w.Header().Set("Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'")
		if name == "" {
			name = "index.html"
		}
		if _, err := fs.Stat(assets, name); err != nil {
			if strings.HasPrefix(name, "assets/") || path.Ext(name) != "" {
				http.NotFound(w, r)
				return
			}
			name = "index.html"
		}
		if name == "index.html" {
			w.Header().Set("Cache-Control", "no-store")
			content, err := fs.ReadFile(assets, "index.html")
			if err != nil {
				http.Error(w, "console unavailable", http.StatusServiceUnavailable)
				return
			}
			w.Header().Set("Content-Type", "text/html; charset=utf-8")
			if r.Method != http.MethodHead {
				_, _ = w.Write(content)
			}
			return
		}
		w.Header().Set("Cache-Control", "no-store")
		copy := r.Clone(r.Context())
		copy.URL.Path = "/" + name
		files.ServeHTTP(w, copy)
	})
}
